name: Generate VUR Index

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Make scripts executable
        run: chmod +x vtools/*.sh

      - name: Generate index
        run: ./vtools/generate.sh

      - name: Commit index
        run: |
          git config user.name "VUR Bot"
          git config user.email "bot@vur.local"
          git add index.json
          git diff --quiet || git commit -m "update index"
          git push